# Generated by Django 6.0.5 on 2026-05-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_itenscompra_preco_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
